import "./GettingStarted.css";

const STEPS = [
  {
    number: "01",
    title: "Project Information",
    description:
      "Enter your subject, semester, course and other project details before generating your document.",
  },
  {
    number: "02",
    title: "Paste Question Sheet",
    description:
      "Paste your practical, assignment or question sheet exactly as provided.",
  },
  {
    number: "03",
    title: "Review Questions",
    description:
      "Verify the parsed questions. Edit, delete or add questions before generation.",
  },
  {
    number: "04",
    title: "Generate Document",
    description:
      "Submitify generates every experiment independently for faster and more reliable results.",
  },
  {
    number: "05",
    title: "Edit Your Document",
    description:
      "Click any text to edit. Insert paragraphs, code blocks and images directly inside the editor.",
  },
  {
    number: "06",
    title: "Export PDF",
    description:
      "Export a professional academic document with optimized print layout and formatting.",
  },
];

export default function GettingStarted() {
  return (
    <div className="guide-page">
      <div className="guide-page-header">
        <span className="guide-page-label">Getting Started</span>

        <h1>Learn the complete workflow in minutes</h1>

        <p>
          Submitify transforms your question sheet into a structured academic
          document that you can edit before exporting as a PDF.
        </p>
      </div>

      <div className="guide-steps">
        {STEPS.map((step) => (
          <div key={step.number} className="guide-step-card">
            <div className="guide-step-number">{step.number}</div>

            <div className="guide-step-content">
              <h3>{step.title}</h3>

              <p>{step.description}</p>
            </div>
          </div>
        ))}
      </div>

      <div className="guide-tip">
        <h4>Tip</h4>

        <p>
          Every section generated by AI remains fully editable before exporting.
          Nothing is locked.
        </p>
      </div>
    </div>
  );
}